@echo off
cd "Linux SWITCH"
CLS
CHOICE /N /C:123 /M "PICK A NUMBER (1, 2, or 3)"%1
echo 1. UBUNTU
echo 2. FEDORA
echo 3. DEBIAN
echo 4. Open CMD
IF ERRORLEVEL ==4 GOTO FOUR
IF ERRORLEVEL ==3 GOTO THREE
IF ERRORLEVEL ==2 GOTO TWO
IF ERRORLEVEL ==1 GOTO ONE
GOTO END
:FOUR
ECHO Loading Ubuntu:XENIAL
ECHO Please Wait.
sleep 1s
ECHO Loading Ubuntu:XENIAL
ECHO Please Wait..
sleep 0.2s
ECHO Loading Ubuntu:XENIAL
ECHO Please Wait...
sleep 0.2s
py ./switch.py ubuntu:xenial
GOTO END
:THREE
ECHO YOU HAVE PRESSED THREE
GOTO END
:TWO
ECHO YOU HAVE PRESSED TWO
GOTO END
:ONE
ECHO YOU HAVE PRESSED ONE
:END